### ISSUE TITLE
Total amount: 0

### ISSUE THREAD

**Issue by piechowiakmichal** [henriksb/RouterPassword-Lookup#3]
Hi!

I will grabbing passwords, does not get an error, it takes some time, the process ends without error.
When I type the command ``RouterPassword --listall`` output is: ``Total amount: 0``.

Can you check it?

**Comment by henriksb** [comment]
I see. They may have changed the website since creating this script. I will make a small change and update the script.

**Comment by piechowiakmichal** [comment]
Thank you!

**Comment by henriksb** [comment]
It should work now. Thank you for letting me know!

**Comment by piechowiakmichal** [comment]
Works good, thank you!
